name: Android Workflow

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Install Android SDK
        uses: android-actions/setup-android@v2
        with:
          sdk-platform: 'platform-31'

      - name: Build and Install APK
        run: |
          adb install -r ./usr/local/automation/MobileApps/corbita_android.apk

#       - name: Run Test Cases
#         run: |
#           # Replace with the commands to run your test cases on the connected Android device
#           ./gradlew connectedAndroidTest


