name: Performance_Script_Workflow

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: self-hosted
    
    steps:
     - name: Checkout Repository
       uses: actions/checkout@v2
       
     - name: Set up JDK
       uses: actions/setup-java@v2
       with:
          java-version: '11'
          
     - name: Run Performance script for Mount drive
       run: |
         -DconfigFilePath=/Users/shrinidhigcw/Desktop/client-automation/src/main/resources/corbita/configs/desktop/mac/mac_install.yml
         -DxmlSuiteFile=/Users/shrinidhigcw/Desktop/client-automation/src/main/resources/corbita/tests/desktop/perfromance/testng_verify_mountdrive.xml
         -Ddataset=/Users/shrinidhigcw/Desktop/client-automation/src/main/resources/corbita/configs/desktop/mac/desktop_mac_node1.properties
         -Dapplication=corbita
         -Dversion=Phase0
         -Dbuild=1.0.0
         -Diterations=1
         -Dhardware=macOS
         mvn test
    
