name: Upload Artifact

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Upload artifact
      run: |
        echo "Uploading artifact..."
        ./upload_artifact.sh
        chmod +x upload_artifact.sh
