name: workflow2
on:
  workflow_dispatch:
    inputs:
      commit_sha:
        required: true
        type : string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
